version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:1.6.7
    restart: always
    ports:
      - 1883:1883
      # - 9001:9001
    volumes:
      # - ./cfg:/mosquitto/config/
      - /mosquitto/data
      - /mosquitto/log
  godor:
    image: cosmtrek/air
    restart: always
    working_dir: /go/src/twitchel/godor/
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./:/go/src/twitchel/godor/
    depends_on:
      - mqtt
    environment:
      - MQTT_SERVER=tcp://mqtt:1883
      - MQTT_TOPIC=godor/door1
    stdin_open: true
    tty: true
  mqtt-client:
    image: efrecon/mqtt-client
    restart: always
    command: sub -h mqtt -t "godor/door1" -v
    depends_on:
      - mqtt
volumes:
  go_src:
  go_pkg:
